apiVersion: v1
kind: Secret
metadata:
  name: customercore-secrets
  namespace: customercore
type: Opaque
data:
  OPENROUTER_API_KEY: c2stb3ItdjEtMjE3NGQ5ZTBjOWQwM2M2MDY5MWEyOWVkOThkODMxZTQ1Y2VjZGU0ZDY0MTg2MWNhOTgyNTY2ZWU5OTA5ZWU0Ng==
  LITELLM_MASTER_KEY: ZGV2LXNlY3JldC1qd3Qtc2lnbmluZy1rZXktcGxhY2Vob2xkZXItb25seQ==
  SUPABASE_URL: aHR0cHM6Ly9meWdwbWZydGZ6ZG5qa2V4aHZ5ay5zdXBhYmFzZS5jbw==
  SUPABASE_ANON_KEY: c2JfcHVibGlzaGFibGVfLVBpTFhkM2g4ZUtSbFcxQW9xQjFrZ19aSXVvY3NQNA==
  SUPABASE_SERVICE_ROLE_KEY: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKemRYQmhZbUZ6WlNJc0luSmxaaUk2SW1aNVozQnRabkowWm5wa2JtcHJaWGhvZG5scklpd2ljbTlzWlNJNkluTmxjblpwWTJWZmNtOXNaU0lzSW1saGRDSTZNVGMzT1RVMk1Ea3pNeXdpWlhod0lqb3lNRGsxTVRNMk9UTXpmUS4wOWhwQXdhV3FOc0ZhQTU1SXFsTzAxVS1NNVFPQjdTRnNSRDA2YVJERVFR
  SUPABASE_DB_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOk5hbWJ1cmlAMjAwNEBkYi5meWdwbWZydGZ6ZG5qa2V4aHZ5ay5zdXBhYmFzZS5jbzo1NDMyL3Bvc3RncmVz
  UPSTASH_REDIS_URL: cmVkaXM6Ly9sb2NhbGhvc3Q6NjM3OQ==
  LANGFUSE_PUBLIC_KEY: cGstbGYtMGFkNTJlM2YtOTQyNS00OTM4LTk2YjktYmM1ZjE1ZDFjZTQy
  LANGFUSE_SECRET_KEY: c2stbGYtMzVlOTAyYTUtZDc5Zi00MTNkLTk2M2EtZjFhMmRhOGU2YzI3
